### ISSUE TITLE
[TEST] 위시리스트 테스트 코드 작성

### ISSUE THREAD

**Issue by stopmin** [kakao-tech-campus-2nd-step3/Team10_BE#120]
### ✏️ Describe

위시리스트 테스트 코드를 작성한다.

### ✅ TO-DO

- [ ] 위시리스트에 상품을 넣는다.
- [ ] 품절된 상품도 위시에 넣을 수 있다.
- [ ] 위시에 정상적으로 제품이 삭제된다.

### 🙋🏻 More

-
