### ISSUE TITLE
토큰 재발급, 이미지, 농부 등업 약간의 수정

### ISSUE THREAD

**Issue by jjt4515** [kakao-tech-campus-2nd-step3/Team10_BE#124]
### ✏️ Describe

필터 안 거침 이슈로 토큰 재발급 코드 약간의 수정
이미지 피드백 반영
농부 등업 권한 관리자 -> 회원 본인으로 변경

### ✅ TO-DO

- [ ] userDetails 대신 헤더에서 access token 추출
- [ ] 이미지 피드백 반영
- [ ] 농부 등업 권한 관리자 -> 회원 본인으로 변경

**Comment by amm0124** [comment]
![image](https://github.com/user-attach여

**Comment by amm0124** [comment]
![image](https://github.com/user-attachments/assets/26f61f34-f87b-4836-ada6-438ea1f030ac)
이거보고하ㅓ심될거같아요
