### ISSUE TITLE
[멤버] 테스트 코드 작성

### ISSUE THREAD

**Issue by jjt4515** [kakao-tech-campus-2nd-step3/Team10_BE#135]
### ✏️ Describe

제가 작성한 코드들에 대해서 테스트 코드 작성할 것입니다.

### ✅ TO-DO

- [ ] 고객 정보 수정 
- [ ] 농부 정보 수정
- [ ] 회원 조회
- [ ] 농부로 전환
- [ ] 회원 전체 요약 조회 
- [ ] 고객으로 전환
- [ ] 일반 회원가입
- [ ] 회원 요약 조회
- [ ] 회원 본인 조회
- [ ] 배송지 수정
- [ ] 회원 탈퇴
- [ ] 회원 계정 복구
- [ ] 회원 계정 정지
