### ISSUE TITLE
장바구니 개수 삭제, order 검증 로직 추가

### ISSUE THREAD

**Issue by canyos** [kakao-tech-campus-2nd-step3/Team10_BE#189]
### ✏️ Describe

장바구니 개수 삭제, order 검증 로직 추가

### ✅ TO-DO

- [ ] 장바구니에서 개수를 삭제
- [ ] order만들 때 개수를 dto로 받기
- [ ] order만들 때 기존 cart 검증하기
