### ISSUE TITLE
[농장] 명세 수정 작업

### ISSUE THREAD

**Issue by stopmin** [kakao-tech-campus-2nd-step3/Team10_BE#196]
### ✏️ Describe

명세를 수정합니다.
- 농장 설명 등록
- 농장 스케쥴 등록 

### ✅ TO-DO

- [x] 농장 설명 등록 API
- [x] 농장 설명 조회 API
- [x] 농장 스케쥴 등록 API

### 🙋🏻 More

-
