### ISSUE TITLE
장바구니를 생성한다

### ISSUE THREAD

**Issue by stopmin** [kakao-tech-campus-2nd-step3/Team10_BE#27]
#### ⭐️ 주요 작업사항
**장바구니를 생성합니다.**
- 장바구니에는 수량 값을 담을 수 있고, 수량이 수정될 수 있습니다.
- 참고로 상품에는 옵션이 없습니다. (4주차 회의 논의 사항입니다.)

Farm은 장바구니 개념이 없습니다. Product에 대해서만 생성해주시면 됩니다. MemberId와 1:1으로 매핑되면 될 것 같습니다.

### ✅ TO-DO

**추가**
- [x] 장바구니에 상품과 그 수량을 선택해 추가할 수 있다.

**삭제** 
> 재사용성을 고려해서 작업하시면 좋겠습니다. (결제 처리시 사용 가능)
- [x] 장바구니를 몽땅 삭제 할 수 있다. 
- [x] 장바구니에 선택한 상품을 삭제할 수 있다.

**수정**
- [x] 장바구니에 있는 상품의 수량을 수정할 수 있다.

**⭐️ 조회**
- 품절 되었을 경우를 대응해야합니다. ➡️ product에 품절 상태가 있는지 확인하신 후 작업 부탁드립니다.

위는 기본적인 작업 사항이고 추가적으로 필요한 작업사항은 같이 작업 부탁드립니다.

### 🙋🏻 More

UI 참고하시면 좋을 것 같습니다. 
Product에 대한 수정이 필요할 것이라고 예상되는데, 수정이 필요하시다면 풍헌님과 커뮤니케이션 해보시고 이번 PR에서 최대한 적게 작업하시는 것을 추천드립니다. 

<img width="531" alt="스크린샷 2024-10-01 오후 4 23 43" src="https://github.com/user-attachments/assets/7b83805f-0326-42d4-84a4-90e314593534">
