### ISSUE TITLE
Farm Schedule 관리 방식 및 금액제도 수정

### ISSUE THREAD

**Issue by stopmin** [kakao-tech-campus-2nd-step3/Team10_BE#62]
### ✏️ Describe

2024.10.11 회의 내용 반영합니다!
기존에는 날짜 단위로 관리했던 일정을 수정합니다. 
금액 책정 방식을 수정합니다.

아래 이미지 참고하시면 될 것 같습니다.
<img width="463" alt="스크린샷 2024-10-11 오후 7 03 40" src="https://github.com/user-attachments/assets/9e319a88-6511-4f56-8e46-50e6d43def42">

### 정리
- 농장은 한팀당 최대 수용 인원/한타임에 최대 수용 팀을 저장할 수 있다.
- 비용은 인원 수로 할당한다.

### ✅ TO-DO

- [x] Farm Schedule에 시간 추가
- [x] 최대 수용 가능 인원으로 수정
- [x] 금액은 인원당 단위로 수정
