### ISSUE TITLE
S3 개선

### ISSUE THREAD

**Issue by jjt4515** [kakao-tech-campus-2nd-step3/Team10_BE#78]
### ✏️ Describe

S3 코드 개선점 발견하여 시간이 있으면 추가할 예정입니다.

### ✅ TO-DO

- [ ] s3 삭제 구현(이미지 저장 실패 시 s3에서도 삭제) 
- [ ] jpg 말고 다른 파일 형식 들어오는 경우 처리
- [ ] url 겹치는 경우 처리
- [ ] url 요청 GET으로 바꾸기
- [ ] 스케줄러 구현해서 이미지에서는 지워졌는데 s3에 남아있는 거 삭제
