### ISSUE TITLE
예약 & 농장 조회 Security 적용

### ISSUE THREAD

**Issue by stopmin** [kakao-tech-campus-2nd-step3/Team10_BE#96]
### ✏️ Describe

1. 시큐리티 적용
2. 예약 관련 Validation BUG 수정

현재, 어드미인지 농장주인지 확인하는 로직에 오류가 있습니다. AND조건으로 둬서 농장주이고, 어드민이어야 읽을 수 있도록 짰네요 ㅠㅠ 미안합니다!

### ✅ TO-DO
시큐리티 적용
- [x] 스케쥴 추가 시큐리티 적용
- [x] 스케쥴 조회 API 수정
- [x] 농장 단건 조회/농장 취소/농장 예약 조회 시큐리티 적용

예약 조회 API 버그 수정
- [x] 권한 확인 로직 개선
